# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8791ad4be5407063791d21f5ee3347f63630d5ca71cab8783ec69ac9cc749a44e25526c04b4f41975e13fd72fbfec3d4826d51dfcb3b13cc1220f3d0379a45e4

test:
  secret_key_base: f5606e4ac4d23323da196594081cf7d9324d895f721984aa7c0033f2794b27fbef821e2a19dff909b897d23a7dc889e34af5835d5de17ddf34f4f6a8f778b522

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
